### ISSUE TITLE
torbrowser-launcher does not init and install the browser

### ISSUE THREAD

**Issue by witcheslive** [MeisterP/torbrowser-overlay#64]
Getting an error when I try to run torbrowser-launcher for the first time. Tried providing a URL but wasn't sure what to provide, nor did it seem to change the error.

```
~ $ torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.3.5
https://github.com/micahflee/torbrowser-launcher
Downloading Tor Browser for the first time.
Downloading https://aus1.torproject.org/torbrowser/update_3/release/Linux_x86_64-gcc3/x/en-US
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.10/torbrowser-launcher", line 30, in <module>
    torbrowser_launcher.main()
  File "/usr/lib/python3.10/site-packages/torbrowser_launcher/__init__.py", line 92, in main
    gui.move(
TypeError: arguments did not match any overloaded call:
  move(self, a0: QPoint): argument 1 has unexpected type 'float'
  move(self, ax: int, ay: int): argument 1 has unexpected type 'float'
```

**Comment by witcheslive** [comment]
freshly installed the overlay as of a few minutes before posting this

**Comment by witcheslive** [comment]
Some more information:

installed with `sudo eselect repository enable torbrowser`

attempting to eshowkw torbrowser-launcher
```
 ~ $ eshowkw torbrowser-launcher
!!! Section 'torbrowser' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/torbrowser'
!!! Section 'torbrowser' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/torbrowser'
No such package "torbrowser-launcher"
```

**Comment by MeisterP** [comment]
What's the output of
`emerge --info torbrowser-launcher`

**Comment by witcheslive** [comment]
```
 ~ $ emerge --info torbrowser-launcher
!!! Section 'torbrowser' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/torbrowser'
WARNING: One or more repositories have missing repo_name entries:

	/var/db/repos/torbrowser/profiles/repo_name

NOTE: Each repo_name entry should be a plain text file containing a
unique name for the repository on the first line.


Portage 3.0.38.1 (python 3.10.8-final-0, default/linux/amd64/17.1/desktop/plasma, gcc-12, glibc-2.36-r5, 6.0.6-gentoo x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-6.0.6-gentoo-x86_64-AMD_Ryzen_9_7950X_16-Core_Processor-with-glibc2.36
KiB Mem:    64870568 total,   2850436 free
KiB Swap:  134217724 total, 134217724 free
Timestamp of repository gentoo: Wed, 09 Nov 2022 16:30:01 +0000
Head commit of repository gentoo: c19157b7dbcf704be07ece0abc0a494ee0b5ce5b
Timestamp of repository guru: Wed, 09 Nov 2022 00:02:02 +0000
Head commit of repository guru: 59070191d103e568b7fc14455e39c20de0210a74

Head commit of repository plex-overlay: a5b400b7d571335016fc7b9e7d6ffcf86c41a69d

Timestamp of repository steam-overlay: Thu, 20 Oct 2022 06:32:14 +0000
Head commit of repository steam-overlay: f40a22632e77a46be0153821f4a7f7847029533b

Timestamp of repository usenet-overlay: Wed, 19 Oct 2022 17:46:52 +0000
Head commit of repository usenet-overlay: d9a17fae1080a867d450f8952099e13091d82195

sh bash 5.1_p16-r2
ld GNU ld (Gentoo 2.39 p5) 2.39.0
app-misc/pax-utils:        1.3.5::gentoo
app-shells/bash:           5.1_p16-r2::gentoo
dev-java/java-config:      2.3.1::gentoo
dev-lang/perl:             5.36.0-r1::gentoo
dev-lang/python:           3.10.8_p2::gentoo, 3.11.0_p1::gentoo
dev-lang/rust-bin:         1.64.0-r1::gentoo
dev-util/cmake:            3.24.3::gentoo
dev-util/meson:            0.64.0::gentoo
sys-apps/baselayout:       2.9::gentoo
sys-apps/openrc:           0.45.2-r1::gentoo
sys-apps/sandbox:          2.29::gentoo
sys-devel/autoconf:        2.13-r7::gentoo, 2.71-r4::gentoo
sys-devel/automake:        1.16.5::gentoo
sys-devel/binutils:        2.39-r4::gentoo
sys-devel/binutils-config: 5.4.1::gentoo
sys-devel/clang:           13.0.1::gentoo, 14.0.6-r1::gentoo, 15.0.4::gentoo
sys-devel/gcc:             12.2.1_p20221008::gentoo
sys-devel/gcc-config:      2.8::gentoo
sys-devel/libtool:         2.4.7::gentoo
sys-devel/lld:             13.0.1-r1::gentoo, 14.0.6-r1::gentoo, 15.0.4::gentoo
sys-devel/llvm:            13.0.1::gentoo, 14.0.6-r2::gentoo, 15.0.4::gentoo
sys-devel/make:            4.4::gentoo
sys-kernel/linux-headers:  6.0::gentoo (virtual/os-headers)
sys-libs/glibc:            2.36-r5::gentoo
Repositories:

gentoo
    location: /var/db/repos/gentoo
    sync-type: rsync
    sync-uri: rsync://rsync.gentoo.org/gentoo-portage
    priority: -1000
    sync-rsync-extra-opts: 
    sync-rsync-verify-jobs: 1
    sync-rsync-verify-max-age: 24
    sync-rsync-verify-metamanifest: yes

guru
    location: /var/db/repos/guru
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/guru.git
    masters: gentoo

plex-overlay
    location: /var/db/repos/plex-overlay
    sync-type: git
    sync-uri: https://github.com/comio/plex-overlay
    masters: gentoo

steam-overlay
    location: /var/db/repos/steam-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/steam-overlay.git
    masters: gentoo

usenet-overlay
    location: /var/db/repos/usenet-overlay
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/usenet-overlay.git
    masters: gentoo

ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="*"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -march=znver3"
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/lib64/libreoffice/program/sofficerc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
CXXFLAGS="-O2 -pipe -march=znver3"
DISTDIR="/var/cache/distfiles"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR XDG_STATE_HOME"
FCFLAGS="-O2 -pipe -march=znver3"
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs binpkg-multi-instance buildpkg-live config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe -march=znver3"
GENTOO_MIRRORS="http://mirrors.rit.edu/gentoo/ http://gentoo-mirror.flux.utah.edu/"
LANG="en_US.utf8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j16"
PKGDIR="/var/cache/binpkgs"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
SHELL="/bin/bash"
USE="X a52 aac acl acpi activities alsa amd64 bluetooth branding bzip2 cairo cdda cdr cli crypt cups dbus declarative dri dts dvd dvdr elogind encode exif flac fortran gdbm gif gpm gtk gui iconv icu ipv6 jpeg kde kwallet lcms libglvnd libnotify libtirpc mad mng mp3 mp4 mpeg multilib ncurses nls nptl ogg opengl openmp pam pango pcre pdf plasma png policykit ppds pulseaudio qml qt5 readline sdl seccomp semantic-desktop spell split-usr ssl startup-notification svg test-rust tiff truetype udev udisks unicode upower usb vorbis vulkan widgets wxwidgets x264 xattr xcb xml xv xvid zlib" ABI_X86="64" ADA_TARGET="gnat_2020" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon sheets words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext sse sse2 aes avx avx2 avx512bw avx512cd avx512dq avx512f avx512vbmi avx512vl f16c fma3 pclmul popcnt rdrand sha sse3 sse4_1 sse4_2 sse4a ssse3" CURL_SSL="nss" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock greis isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" GRUB_PLATFORMS="efi-64" INPUT_DEVICES="libinput" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" LUA_SINGLE_TARGET="lua5-1" LUA_TARGETS="lua5-1" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php7-4 php8-0" POSTGRES_TARGETS="postgres12 postgres13" PYTHON_SINGLE_TARGET="python3_10" PYTHON_TARGETS="python3_10" QEMU_SOFTMMU_TARGETS="x86_64" QEMU_USER_TARGETS="x86_64" RUBY_TARGETS="ruby27" USERLAND="GNU" VIDEO_CARDS="amdgpu radeonsi" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq proto steal rawnat logmark ipmark dhcpmac delude chaos account"
Unset:  ADDR2LINE, AR, ARFLAGS, AS, ASFLAGS, CC, CCLD, CONFIG_SHELL, CPP, CPPFLAGS, CTARGET, CXX, CXXFILT, ELFEDIT, EMERGE_DEFAULT_OPTS, EXTRA_ECONF, F77FLAGS, FC, GCOV, GPROF, INSTALL_MASK, LC_ALL, LD, LEX, LFLAGS, LIBTOOL, LINGUAS, MAKE, MAKEFLAGS, NM, OBJCOPY, OBJDUMP, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS, RANLIB, READELF, RUSTFLAGS, SIZE, STRINGS, STRIP, YACC, YFLAGS

=================================================================
                        Package Settings
=================================================================

www-client/torbrowser-launcher-0.3.5-r2::guru was built with the following:
USE="-apparmor" ABI_X86="(64)" PYTHON_TARGETS="python3_10 -python3_8 -python3_9"
```

**Comment by MeisterP** [comment]
> www-client/torbrowser-launcher-0.3.5-r2::guru

your version is installed from the guru overlay. it's not the one from the torbrowser overlay.

**Comment by witcheslive** [comment]
hmm, I ran the command from the instructions, `eselect repository enable torbrowser`. my apologies if I'm missing something basic, but may I ask what might have gone wrong and how to fix it?

**Comment by MeisterP** [comment]
> `!!! Section 'torbrowser' in repos.conf has location attribute set to nonexistent directory: '/var/db/repos/torbrowser'`

looks like you configured the overlay, but never actually synced it
does `emaint sync -r torbrowser` work?
did you follow the steps at https://wiki.gentoo.org/wiki/Eselect/Repository to setup eselect-repository?

**Comment by witcheslive** [comment]
ah there we go. i temporarily disabled the guru overlay (and then did some fiddling with some gtk wayland use flags argle garble wayland etc etc) and did a sync and it works now. thank you for your time and patience!
