### ISSUE TITLE
Possible issue when running under python 3.12?

### ISSUE THREAD

**Issue by realkinetix** [MeisterP/torbrowser-overlay#78]
``
$ /usr/lib/python-exec/python3.12/torbrowser-launcher
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/torbrowser-launcher", line 30, in <module>
    import torbrowser_launcher
  File "/usr/lib/python3.12/site-packages/torbrowser_launcher/__init__.py", line 37, in <module>
    from .common import Common, SHARE
  File "/usr/lib/python3.12/site-packages/torbrowser_launcher/common.py", line 37, in <module>
    import gpg
  File "/usr/lib/python3.12/site-packages/gpg/__init__.py", line 123, in <module>
    from . import core
  File "/usr/lib/python3.12/site-packages/gpg/core.py", line 10, in <module>
    from . import gpgme
ImportError: cannot import name 'gpgme' from partially initialized module 'gpg' (most likely due to a circular import) (/usr/lib/python3.12/site-packages/gpg/__init__.py)
``

Seems happy under python3.11:

``
$ /usr/lib/python-exec/python3.11/torbrowser-launcher
Tor Browser Launcher
By Micah Lee & Tor Project, licensed under MIT
version 0.3.7
``

**Comment by redblade7** [comment]
I just installed torbrowser-launcher and have the same problem.
